name = "salesio-festa-pc2026"
compatibility_date = "2024-09-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "myDatabase"
database_name = "salesio-pc2026-statistics"
database_id = "5a798cff-1173-4d96-9098-798934c7b92a"
